addon.name     = 'rtfm'
addon.author   = 'Rialia'
addon.version  = '0.0.1'
addon.desc     = 'Learning addon: parse log lines step by step.'
addon.commands = { 'rtfm' }

require('common')

------------------------------------------------------------
-- Data
------------------------------------------------------------
local mob_data = require('data.mobs')

local base_path = AshitaCore:GetInstallPath()
local data_dir  = base_path .. 'addons\\rtfm\\data'
local learned_path = data_dir .. '\\mobs_learned.lua'

local learned_mobs = {}

------------------------------------------------------------
-- State / Config
------------------------------------------------------------
local show_all_mobs = true
local pending_move  = nil
local active_move   = nil

local learned_dirty = false
local last_save     = os.clock()

print('[RTFM] addon loaded')

------------------------------------------------------------
-- Helpers
------------------------------------------------------------
local function strip_formatting(s)
    if not s then return '' end
    return s:gsub('[\31\30\127]', '')
end

-- Ensure a directory exists (Windows-safe)
local function ensure_directory(path)
    os.execute(string.format('mkdir "%s"', path))
end

------------------------------------------------------------
-- Load learned data if present
------------------------------------------------------------
do
    local ok, data = pcall(dofile, learned_path)
    if ok and type(data) == 'table' then
        learned_mobs = data
        print('[RTFM] Loaded learned mob data.')
    end
end

------------------------------------------------------------
-- Normalize learned data (upgrade old formats safely)
------------------------------------------------------------
for _, data in pairs(learned_mobs) do
    data.moves = data.moves or {}
    for move, v in pairs(data.moves) do
        if v == true then
            data.moves[move] = { notes = "" }
        elseif type(v) == 'table' and v.notes == nil then
            v.notes = ""
        end
    end
end

------------------------------------------------------------
-- Record a mob + move (learning always ON)
------------------------------------------------------------
local function learn_mob_move(mob, move)
    learned_mobs[mob] = learned_mobs[mob] or { moves = {} }

    if not learned_mobs[mob].moves[move] then
        learned_mobs[mob].moves[move] = {
            notes = "",
        }
        learned_dirty = true
        print(string.format('[RTFM] Learned: %s → %s', mob, move))
    end
end

------------------------------------------------------------
-- Save learned data (throttled, safe)
------------------------------------------------------------
local function save_learned()
    if not learned_dirty then return end

    -- Ensure data directory exists
    ensure_directory(data_dir)

    local f, err = io.open(learned_path, 'w')
    if not f then
        print('[RTFM] ERROR: Could not write mobs_learned.lua')
        print('[RTFM] Lua error: ' .. tostring(err))
        return
    end

    f:write('-- AUTO-GENERATED FILE (DO NOT EDIT)\n')
    f:write('-- Generated by RTFM learn mode\n\n')
    f:write('return {\n')

    for mob, data in pairs(learned_mobs) do
        f:write(string.format('    ["%s"] = {\n', mob))
        f:write('        moves = {\n')
        for move, info in pairs(data.moves) do
            f:write(string.format('            ["%s"] = {\n', move))
            f:write(string.format('                notes = "%s",\n', info.notes or ""))
            f:write('            },\n')
        end
        f:write('        },\n')
        f:write('    },\n')
    end

    f:write('}\n')
    f:close()

    learned_dirty = false
    last_save = os.clock()

    print('[RTFM] Learned mob data saved.')
end

------------------------------------------------------------
-- Event: text_in
------------------------------------------------------------
ashita.events.register('text_in', 'rtfm_text_in', function (e)
    if not e or e.injected or not e.message then return end

    local msg = strip_formatting(e.message):trim()

    --------------------------------------------------------
    -- READIES
    --------------------------------------------------------
    local monster, move = msg:match('^%s*(.-)%s+readies%s+([^%.]+)')
    if monster and move then
        move = move:gsub('[%p%d%s]+$', '')

        local mob_entry = mob_data[monster] or learned_mobs[monster]
        if not show_all_mobs and not mob_entry then
            return
        end

        pending_move = {
            mob   = monster,
            move  = move,
            time  = os.clock(),
            entry = mob_entry,
        }

        local tag = mob_entry and (mob_entry.nm and 'NM' or 'Mob') or 'Unlisted'
        print(string.format('[RTFM] %s | %s readies %s', tag, monster, move))
        return
    end

    --------------------------------------------------------
    -- USES (with optional inline damage)
    --------------------------------------------------------
    local umob, umove, target, dmg =
        msg:match('^%s*(.-)%s+uses%s+([^%.]+)%.?%s*(.-)%s+takes%s+(%d+)%s+points%s+of%s+damage')

    if not umob then
        umob, umove = msg:match('^%s*(.-)%s+uses%s+([^%.]+)')
    end

    if umob and umove then
        umove = umove:gsub('[%p%d%s]+$', '')

        -- Always learn
        learn_mob_move(umob, umove)

        local entry
        if pending_move and pending_move.mob == umob and pending_move.move == umove then
            entry = pending_move.entry
            pending_move = nil
        else
            entry = mob_data[umob] or learned_mobs[umob]
            if not show_all_mobs and not entry then
                return
            end
        end

        active_move = {
            mob   = umob,
            move  = umove,
            hits  = {},
            time  = os.clock(),
            entry = entry,
        }

        if target and dmg then
            table.insert(active_move.hits, {
                target = target,
                damage = tonumber(dmg),
            })
            active_move.time = os.clock()
        end

        return
    end

    --------------------------------------------------------
    -- DAMAGE (separate line)
    --------------------------------------------------------
    if active_move then
        local target, dmg = msg:match('^(%S+) takes (%d+) points of damage')
        if target and dmg then
            table.insert(active_move.hits, {
                target = target,
                damage = tonumber(dmg),
            })
            active_move.time = os.clock()
            return
        end
    end

    --------------------------------------------------------
    -- FINALIZE
    --------------------------------------------------------
    if active_move and os.clock() - active_move.time > 1.5 then
        local tag = active_move.entry and (active_move.entry.nm and 'NM' or 'Mob') or 'Unlisted'

        print(string.format(
            '[RTFM] %s | %s used %s on %d target(s)',
            tag,
            active_move.mob,
            active_move.move,
            #active_move.hits
        ))

        for _, hit in ipairs(active_move.hits) do
            print(string.format('  - %s (%d dmg)', hit.target, hit.damage))
        end

        active_move = nil
    end

    --------------------------------------------------------
    -- AUTO-SAVE LEARNED DATA (every 10s if dirty)
    --------------------------------------------------------
    if learned_dirty and os.clock() - last_save > 10 then
        save_learned()
    end
end)
