-- AUTO-GENERATED FILE (DO NOT EDIT)
-- Generated by RTFM learn mode

return {
    ["The Greater Manticore"] = {
        moves = {
            ["Great Whirlwind"] = {
                notes = "",
            },
            ["Deadly Hold"] = {
                notes = "",
            },
            ["Riddle"] = {
                notes = "",
            },
            ["Tail Smash"] = {
                notes = "",
            },
            ["Tail Swing"] = {
                notes = "",
            },
        },
    },
}
